### ISSUE TITLE
Make `Option` generic

### ISSUE THREAD

**Issue by Fedeorlandau** [Fedeorlandau/chakra-ui-simple-autocomplete#4]
We should allow Option to be generic. Cheers,

**Comment by anubra266** [comment]
Could you expatiate on this?

**Comment by Fedeorlandau** [comment]
@anubra266 sure

The current codebase allow a pre-defined `Option options` to be passed to the component. Should be nice if we can make the component accept a generic type of Option. Value and Label should be mandatory on that generic type.
