### ISSUE TITLE
Enhancement Request: Prop to Prevent Rendering of Badges

### ISSUE THREAD

**Issue by danbunkr** [Fedeorlandau/chakra-ui-simple-autocomplete#6]
Love the component but for our use case we don't want to render badges as we are only allowing a select limit of 1. The rederBadge function could return null but the <Box> with the margin would still render. I think a simple prop to turn off badge rendering would be a great addition. I can open a PR if you are open to allowing this.

Cheers

**Comment by Fedeorlandau** [comment]
@danbunkr thank you for raising this! Absolutely, feel free to create a PR!

**Comment by csirianni** [comment]
@Fedeorlandau I just made a PR for this issue. Let me know what you think.

**Comment by Fedeorlandau** [comment]
Available on latest release, thank you @csirianni
